### PR TITLE
Fix String array marshal type.

### PR DESCRIPTION
**Pull request by Krixtalx**
Some ImGui methods(such as igListBox_Str_arr) throwing exceptions due to marshal type. This commit fix the problem in PointNet, so it should be pretty general.

### CODE REVIEW

**Comment by tuket** [comment]
Hello, I was wondering if the change that fixes your problem is this one:

```cs
return "[MarshalAs(UnmanagedType.LPArray, ArraySubType = UnmanagedType.LPStr)] string[]";
```

I see other changes related to bool pointers.
I'm not sure if those are necessary.

I'm bringing that up because some time ago I made another PR to fix marshalling issues related too bools. https://github.com/EvergineTeam/ImGui.Net/pull/5

I learned that bools in C# are 4 bytes, whilst, in C/C++, the are 1 byte. Most of the times, it would work because 3 the remaining bytes where 0, but occasionally it would be interpreted incorrectly.
Just wanted to mention it so you can have that in mind :)
Cheers

**Comment by Krixtalx** [comment]
Yeah, that's the only line I changed. The others changed in result of running the generator. It seems that some of the bools marshal changes you made are being taken by the generator.

**Comment by davilovick** [comment]
Hey! I summoned @jcant0n to see this PR :)

**Comment by tuket** [comment]
> Yeah, that's the only line I changed. The others changed in result of running the generator. It seems that some of the bools marshal changes you made are being taken by the generator.

Ah, ok. Interesting... I think that means that the auto-gen code was not regenerated correctly back then, because those changes should have shown up in my PR.

Now I'm suspicious that this change I made back then might be wrong:

chrome_v3KXFCahET

I think it should be `return "byte*";` instead.

Sorry for the confusion :S

**Comment by Krixtalx** [comment]
Np, gonna fix it right now.

**Comment by davilovick** [comment]
I'll call you tomorrow @Krixtalx  and review this PR with you :)

**Comment by jcant0n** [comment]
About a year ago, we made the opposite change:
image

So let's talk about this in a meeting tomorrow.

**Pull request merged**
